In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 23.2.1 -> 23.3.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [2]:
import numpy as np
list1=[2,4,6,8]
array1=np.array(list1)
print(array1)

[2 4 6 8]


In [5]:
import numpy as np
#create a 2D array with 2 rows and 4 columns
array1 = np.array([[1,2,3,4],[5,6,7,8]])
print(array1)

[[1 2 3 4]
 [5 6 7 8]]


In [11]:
import numpy as np
#create a 3D array with"2slices", each of 3 rows and 4 columns
array1 = np.array([[[[1,2,3,4],
                    [5,6,7,8],
                    [9,10,11,12]],

                    [[13,14,15,16],
                    [17,18,19,20],
                    ]]])
print(array1)


ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 2 dimensions. The detected shape was (1, 2) + inhomogeneous part.

In [12]:
import numpy as np
#create an array of integers
array1=np.array([2,4,6])
print(array1.dtype)

int32


In [17]:
import numpy as np
#create an array of integers
int_array = np.array([-3,-1,1])
#floatnumbers
float_array=np.array([0.1,0.2,0.3])
#complex array
complex_array=np.array([1+2j,2+3j,3+4j])
print(int_array.dtype)
print(float_array.dtype)
print(complex_array.dtype)


int32
float64
complex128


In [19]:
import numpy as np 
#create an array of intergers
int_array=np.array([1,3,5,7])
#convert data types of int_array to float
float_array=int_array.astype('float')
#print the array and their data types
print(int_array,int_array.dtype)
print(float_array,float_array.dtype)

[1 3 5 7] int32
[1. 3. 5. 7.] float64


In [ ]:
#attributes:description                 
#ndim:returns number of dimension of the array
#size:returns number of elements of array
#dtype:returns data type of elements in the array
#shape:returns the size of the array in each dimension
#itemsize:returns the size(inbytes) of each elements in the array
#data:returns the buffer containing actual element of each the array in memory

In [3]:
import numpy as np 
#create a 2d array
#use of ndim(returns number of dimension of the array)
array1=np.array([[2,4,6],[1,4,5]])
print(array1.ndim)
print(array1.shape)
print(array1.itemsize)

2
(2, 3)
4
